name 'ubuntu'
maintainer 'Chef Software, Inc.'
maintainer_email 'cookbooks@chef.io'
license 'Apache-2.0'
description 'Sets up apt sources for Ubuntu Linux'
version '3.0.0'
supports 'ubuntu'

source_url 'https://github.com/chef-cookbooks/ubuntu'
issues_url 'https://github.com/chef-cookbooks/ubuntu/issues'
chef_version '>= 13'
